### ISSUE TITLE
List index error when files lacks ending \n

### ISSUE THREAD

**Issue by qholness** [julvo/reloading#3]
This block
```python
s, end = locate_loop_body(tree, loop)
lines  = src.split('\n')
if end < 0:
    end = len(lines)    
body_lines = lines[s-1:end-1]
```
Examines the file and returns the range(s-1:end-) for looping.

If the end of a file is the same as the end of a loop, this results in ```s-1 = end-1```.
This then causes ```body_lines = []``` which causes an IndexError further down.

**Comment by julvo** [comment]
Thanks for reporting this - it's fixed now in v0.1.1.
