### ISSUE TITLE
Pull request for local variable overwrite bug

### ISSUE THREAD

**Issue by iafisher** [julvo/reloading#4]
Hi julvo,

Cool project! There's a bug where local variables defined in `reloading/reloading.py` overwrite local variables in the user's code.

For example, this snippet prints the name of the file it is defined in, instead of the string `test`, because of [this variable definition in reloading.py](https://github.com/julvo/reloading/blob/master/reloading/reloading.py#L57).

```python
from reloading import reloading

fpath = "test"

for _ in reloading(range(2)):
    print(fpath)
```

I have a patch which I believe fixes the issue. Do you want me to submit a pull request so you can take a look?

**Comment by julvo** [comment]
Hi iafisher, 
Thanks for reporting this - I didn't consider this at all and this could lead to some seemingly weird bugs. I've added a patch myself, as I wanted to add more testing as well.

If you like, you can have a look in [this branch](https://github.com/julvo/reloading/blob/32048339a67d63c638159627b2e28ccfbef3a8c2/reloading/reloading.py#L86) and let me know if you'd see a more elegant solution. What I did was simply avoiding defining new variables after the user's variables are loaded by wrapping the source-loading logic into a function.

**Comment by iafisher** [comment]
I took a different approach, so I'll go ahead and submit a pull request and you can decide which one you like better. Thanks for getting back to me!

**Comment by julvo** [comment]
Thanks for opening the PR. I like your version better - it's shorter and passing dicts to exec seems to be more idiomatic.
