### ISSUE TITLE
AttributeError: 'Attribute' object has no attribute 'id'

### ISSUE THREAD

**Issue by wpf535236337** [julvo/reloading#5]
"File "/usr/local/lib/python3.7/site-packages/reloading/reloading.py", line 16, in find_loop
    if child.iter.func.id == 'reloading':"
when using in python version==3.7，there goes wrong？

**Comment by julvo** [comment]
I'm not sure what's happening there. Would you be able to provide an example of a source file that leads to this error so that I can reproduce it?

**Comment by julvo** [comment]
Closing this for now as this issue became a bit old. Feel free to reopen at any time with more details on how to reproduce the error.

**Comment by sindrig** [comment]
This source file will throw this error:

```
import reloading

@reloading.reloading
def handle():
    pass

handle()
```

Changing the import to `from reloading import reloading` and updating the decorator accordingly fixes it.
